# DerbyPi Ansible Inventory
# Used for both local ansible-pull and remote management

all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3

  children:
    derbypi:
      hosts:
        derbynetpi:
          ansible_host: 192.168.100.10
          ansible_user: derbynet
          ansible_python_interpreter: /usr/bin/python3
